# Build JAVA applications using Apache Maven (http://maven.apache.org)
#

# * Caches downloaded dependencies and plugins between invocation.
# * Verify

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -f Solution/pom.xml"

image: maven:3.6-jdk-11-slim

cache:
  paths:
    - .m2/repository

.verify: &verify
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS verify'

verify:jdk11:
  <<: *verify